### ISSUE TITLE
Gradle applicationID variable

### ISSUE THREAD

**Issue by kubecz3k** [ranmaru90/Play-Game-Services-Android-Module-for-Godot#2]
Hello, I was able to integrate the module with Godot, but unfortunately the app was crashing for me on startup with an error: 
```
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: Incorrect provider authority in manifest. Most likely due to a missing applicationId variable in application's build.gradle.
```
I was able to overpass it by adding a line to `build.gradle.template`  file of Godot soures with:
`
	defaultConfig {
                (...)
		applicationId "com.your.app.package.name"
        }
`
But this has downsides since I need to remember to update the file every-time I update Godot (and also this particular Godot sources are tightly associated with this concrete game. )
I'm wondering, is there any other way?

**Comment by ranmaru90** [comment]
This is weird. I tried but I cannot reproduce it.

**Comment by ranmaru90** [comment]
OK I have just updated my Android SDK and I got the same problem. Gonna see what can be done.

**Comment by ranmaru90** [comment]
We [can now add to the defaultConfig section from the module](https://github.com/godotengine/godot/commit/e74d71a5bfccec42945836c82521469ec664b6dc). So, I've done some updates on the config.py and instructions.

**Comment by kubecz3k** [comment]
@ranmaru90 Awesome!
