### ISSUE TITLE
[bug] Google services are trying to login infinitely if no internet connection.

### ISSUE THREAD

**Issue by kubecz3k** [ranmaru90/Play-Game-Services-Android-Module-for-Godot#3]
I have noticed that this module is trying to login infinitely if there is no internet connection (or connection is weak). After looking on source I think the guilty is `OnConnectionFailedListener`  which is trying to reconnect  (then connection is failing so it'strying to reconnect once more etc).
I think in case of error there should be some sort of callback to gdscript, that would allow developers to decide on their own what to do (reconnect, show error message, ignore).

**Comment by kubecz3k** [comment]
Eventually maybe this call comes from `onMainActivityResult` <- I'm not exactly sure in what circumstances android is calling this function.

**Comment by kubecz3k** [comment]
Also as far as I can tell this can  be tested by turning on airplane mode before running freshly installed game.

**Comment by ranmaru90** [comment]
In your developer's console, under "Game Details", there's a tiny section at the bottom titled "API Console Project". Then there's:

This game is linked to the API console project called 'Your Game'. Click on 'Your Game' and you'll be led to another page. Then click "Enabled APIs" and see if all the APIs are enabled for your game. 

I did that and the problem went away.

**Comment by ranmaru90** [comment]
I have done something about it. Please get the latest source and test again.

**Comment by kubecz3k** [comment]
I have tested the changes and I was unable to reproduce this anymore. Thanks a lot!
