### ISSUE TITLE
Globals.has_singleton("PlayGameServices") returns false

### ISSUE THREAD

**Issue by JoshNinetySeven** [ranmaru90/Play-Game-Services-Android-Module-for-Godot#4]
Globals.has_singleton("PlayGameServices") returns false / Globals.get_singleton("PlayGameServices") returns null

I 've followed all the steps of the documentation.
-> compiled the project and got the release.apk.
-> used this as release.apk custom export (release) template.
-> pasted following in engine.cfg:
[Android]
modules="org/godotengine/godot/PlayGameServices"

-> used your code snippet:
<img width="695" alt="snippet" src="https://cloud.githubusercontent.com/assets/22002584/18245238/6a3375e6-7364-11e6-8a14-a58381ceae9a.png">

but when I export it and push the .apk on my phone i will get for Globals.has_singleton("PlayGameServices") false

I decompiled the .apk on the internet and found "PLayGameServices.java" in /org/godotengine/godot/: So what is the problem??
<img width="1050" alt="decompiled" src="https://cloud.githubusercontent.com/assets/22002584/18245772/670fdea6-7367-11e6-98af-4a196446ac89.png">

**Comment by ranmaru90** [comment]
> [Android]
modules="org/godotengine/godot/PlayGameServices"

try changing it to

> [**a**ndroid]
>
> modules="org/godotengine/godot/PlayGameServices"

**Comment by JoshNinetySeven** [comment]
ok, i changed this part, but the situation is the same

**Comment by JoshNinetySeven** [comment]
ok, thats it (stupid typing error)
Thanks for your quick reply
you saved my day

**Comment by ranmaru90** [comment]
Happy to help.
